language: node_js
node_js:
- node
after_success:
- npm run coveralls
deploy:
  provider: npm
  email: ducksource@duckpond.ch
  edge: true
  api_key:
    secure: QUFKETVMkc0j5QT5ek1wSJwglSozhXEhv2Eplf6qKNY1OwiE3IJtm9eDxLPlYFlj3dDMRzlsVWupjGpq/XUmnwfLyJOm1Gt5AnEor0SC74BvYX2fDLP0BupZetsr/inPSQ6ZBrAqCNpr9EqCh7pEN78J+v+KIJHgj8sJ1AXb41jJalGQJ8/ADjdunPF2zPFBcYeDPR4l5AgBOw2SjhZqG+SCaXPLcV7fCoOiL8mTS1MgkROoVAH3v24XckbkHgzbL25UwbSCypdsxXszyuIjJMjkmmNmjUO7KvEGwIRgiGD1OB0QuMoOtvp1gUyanVyXcRQ9GvanluO/yIwy6eJIUi8Gdbp6Nsl0Q6H1zYg3isQGedYgp6ZMbUyEov/CBqP/8U4QHAo/yZjlfuhU3WJUXsyKp0+wIZ9hrDH9mwraJR+OGRIkolpZpnX9rXmM7HVT9JtED/vhzQiyR2XWyGUkyhMWz0EUCG3srDWvegmNLqJF7jM9upxkNpmXTOEWZuChMgvHbUgsbeH3TjLr6iV59i/Ju2h2logoFIdCkOC+ScRuNbJwjTsk99mZLuc+eMDfHStEo1qLFVs/daQmQzp70ZWWDbuck49MtIdAn8LeY0gMNxQ8gEYSbxw4yHCdSjU/BXQFr463/7xDC4X444H8n+WAEjsl5bqayfLI9HmDWxE=
  on:
    tags: true
    repo: Enteee/plantuml-parser
